apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-csi-zrs
parameters:
  skuname: Standard_ZRS
provisioner: disk.csi.azure.com
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
# allowedTopologies:
# - matchLabelExpressions:
#   - key: failure-domain.beta.kubernetes.io/zone
#     values:
#     - centralus-1
#     - centralus-2